DESC FILE;

DESC COMMUNITY;

INSERT ALL INTO gamer VALUES ('qw','qw','qw',null,null) SELECT * FROM DUAL;
commit;
INSERT ALL INTO COMMUNITY (COMMUNITY_ID,COMMUNITY_NAME,COMMUNITY_CONTENT,COMMUNITY_WRITE_TIME,GAMER_ID,READ_COUNT) 
VALUES (SEQ_COMMUNITY_ID.nextval, 'SDAF', 'ASDF', default, 'qw', default) SELECT * FROM DUAL	;


INSERT ALL 	INTO BOARD (BOARD_ID,SUBJECT,CONTENT,WRITE_TIME,LOG_IP,BOARD_WRITER,READ_COUNT) 		
VALUES (SEQ_BOARD_ID.nextval, ?, ?, default, ?, ?, default) 	
SELECT * FROM DUAL ;

SELECT * FROM DUAL ;


SELECT COMMUNITY_ID,COMMUNITY_NAME,COMMUNITY_CONTENT,COMMUNITY_WRITE_TIME,GAMER_ID,READ_COUNT FROM COMMUNITY WHERE COMMUNITY_ID=2;

select * from filES;
SELECT FILE_ID, COMMUNITY_ID, FILE_PATH, FILE_ORIGINAL FROM FILES WHERE COMMUNITY_ID=2;