CREATE SEQUENCE SEQ_TEST;
DROP SEQUENCE SEQ_TEST;
SELECT SEQ_TEST.NEXTVAL FROM DUAL;

DESC DEPT;
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES((SELECT NVL(MAX(DEPTNO),0)+1 FROM DEPT), 'KH','SEOUL');

DROP SEQUENCE SEQ_DEPT_DEPTNO;
CREATE SEQUENCE SEQ_DEPT_DEPTNO
START WITH 78;
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES(SEQ_DEPT_DEPTNO.NEXTVAL, 'KH','SEOUL');

--NEXTVAL은 실패해도 카운트가 올라감

SELECT SEQ_DEPT_DEPTNO.NEXTVAL FROM DUAL;
SELECT SEQ_DEPT_DEPTNO.CURRVAL FROM DUAL;

ALTER SEQUENCE SEQ_DEPT_DEPTNO MAXVALUE 99 CYCLE;

DROP SEQUENCE SEQ_DEPT_DEPTNO;
CREATE SEQUENCE SEQ_DEPT_DEPTNO START WITH 70 
MAXVALUE 99 CYCLE;

SELECT * FROM user_sequences;
DELETE FROM DEPT WHERE DEPTNO >69;
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES(SEQ_DEPT_DEPTNO.NEXTVAL, 'KH','SEOUL');

SELECT * FROM DEPT;
SELECT * FROM EMP;
INSERT ALL
    INTO EMP (EMPNO,ENAME,DEPTNO) VALUES(9999,'홍길동',SEQ_DEPT_DEPTNO.NEXTVAL)
    INTO DEPT VALUES(SEQ_DEPT_DEPTNO.NEXTVAL,'KH','서울')
SELECT * FROM DUAL;

